[project]
name = "dehessen-download"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imagecodecs>=2026.8.16",
    "mercantile>=1.2.1",
    "numpy>=2.5.2",
    "pmtiles>=3.7.0",
    "rasterio>=1.5.1",
    "requests>=2.34.2",
]
